name: "Automatic PR creation"

on:
  push:
    branches:
      - "master"

jobs:
  raise-pr:
    name: Raise PR to production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/github-script@v4
        name: "Raise Pull Request"
        with:
          script: |
            const script = require('./.github/workflows/pullRequestAction.cjs')
            await script({github, context})
