name: "Version Increment and PR Creation"

on:
  workflow_dispatch:
    inputs:
      versionType:
        description: "Version type (patch, minor, major)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  version-and-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/github-script@v4
        name: "Increment Version and Raise Pull Request"
        with:
          script: |
            const script = require('./.github/workflows/incrementVersionAndCreatePR.cjs')
            await script({
              github,
              context,
              versionType: '${{ github.event.inputs.versionType }}'
            })
